server:
  port: 8082
spring:
  application:
    name: sshcrud
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//52.199.163.241:1539/FREEPDB1
    username: JPTCRSDBA1
    password: JPTCRSDBA1
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    database: ORACLE
    show-sql: true
    open-in-view: false
  output:
    ansi:
      enabled: ALWAYS
# DBFile is in the classpath:public/dbfile/world.sql