server:
  port: 8082
spring:
  application:
    name: sshcrud
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://52.199.163.241:5432/world
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 30
      max-lifetime: 1500000
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    org.jooq.tools.LoggerListener: DEBUG
# DBFiles are in the classpath:public/dbfiles/*